server:
  port: 8081
spring:
  application:
    name: myservice
  datasource:
    url: jdbc:mysql://localhost:3306/bianyishop
    username: root
    password: yangbin@me
eureka:
  instance:
    lease-expiration-duration-in-seconds: 5 # 5秒发送一次
    lease-renewal-interval-in-seconds: 15 # 15秒不发送就过期
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: com.yangbin.elasticsearch.pojo